### ISSUE TITLE
Messes with admin bar's searchbox.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/materialize#1]
It causes it to increase in height and thus so does the admin bar itself:

![backdrop-contrib_themes-materialize-messes_with_admin_bar_search_box](https://cloud.githubusercontent.com/assets/2423362/9292084/f1b2abb2-4427-11e5-90bf-9565e1013ed6.png)

**Comment by biolithic** [comment]
should be fixed in latest push, thanks for raising this issue

**Comment by biolithic** [comment]
appears to be fixed in https://github.com/backdrop-contrib/materialize/tree/1.x-1.3.0
